### PR TITLE
Client

### PR DESCRIPTION
**Pull request by mdalpozzo**
Last pull request of this big batch. Again, sorry it's a lot.

this should set up my components and retrieve review data from db.
should render info to browser, very simple

@ysera11

### CODE REVIEW

**Review by chrishanyu — CHANGES_REQUESTED** [review]
Use destructing for 'props'

**Comment by mdalpozzo** [comment]
@ysera11 first, I merged all the branches and master should be good except this last pull request.  I'm not sure where you mean to use destructuring.  I think maybe my commits where just very confusing.  Take another look and let me know.  Then I can merge this branch, delete it, and my master will be all tidy again.  Then I'll work on writing tests and send them along to you asap.

thank you sir.

**Review by chrishanyu — COMMENTED** [review]
use { reviews } instead of props,reviews 👍  otherwise it's good

**Comment by mdalpozzo** [comment]
@ysera11 gotcha man.  fixed it. check it out thanks!

**Comment by chrishanyu** [comment]
Looks good! Go ahead and merge

**Pull request merged**
